#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-hibernate-validator
Version  : 4.3.0.final
Release  : 1
URL      : https://github.com/hibernate/hibernate-validator/archive/4.3.0.Final.tar.gz
Source0  : https://github.com/hibernate/hibernate-validator/archive/4.3.0.Final.tar.gz
Source1  : http://repo1.maven.org/maven2/org/hibernate/hibernate-validator-parent/4.3.0.Final/hibernate-validator-parent-4.3.0.Final.pom
Source2  : http://repo1.maven.org/maven2/org/hibernate/hibernate-validator/4.3.0.Final/hibernate-validator-4.3.0.Final.jar
Source3  : http://repo1.maven.org/maven2/org/hibernate/hibernate-validator/4.3.0.Final/hibernate-validator-4.3.0.Final.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-hibernate-validator-data = %{version}-%{release}
Requires: mvn-hibernate-validator-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# Hibernate Validator
*Version: 4.3.0.Final, 09.05.2012*
## What is it?
This is the reference implementation of JSR 303 - Bean Validation.
Bean Validation defines a metadata model and API for JavaBean validation.
The default metadata source is annotations, with the ability to override and extend
the meta-data through the use of XML validation descriptors.

%package data
Summary: data components for the mvn-hibernate-validator package.
Group: Data

%description data
data components for the mvn-hibernate-validator package.


%package license
Summary: license components for the mvn-hibernate-validator package.
Group: Default

%description license
license components for the mvn-hibernate-validator package.


%prep
%setup -q -n hibernate-validator-4.3.0.Final

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-hibernate-validator
cp copyright.txt %{buildroot}/usr/share/package-licenses/mvn-hibernate-validator/copyright.txt
cp license.txt %{buildroot}/usr/share/package-licenses/mvn-hibernate-validator/license.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/hibernate/hibernate-validator-parent/4.3.0.Final
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/hibernate/hibernate-validator-parent/4.3.0.Final/hibernate-validator-parent-4.3.0.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/hibernate/hibernate-validator/4.3.0.Final
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/hibernate/hibernate-validator/4.3.0.Final/hibernate-validator-4.3.0.Final.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/hibernate/hibernate-validator/4.3.0.Final
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/hibernate/hibernate-validator/4.3.0.Final/hibernate-validator-4.3.0.Final.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/hibernate/hibernate-validator-parent/4.3.0.Final/hibernate-validator-parent-4.3.0.Final.pom
/usr/share/java/.m2/repository/org/hibernate/hibernate-validator/4.3.0.Final/hibernate-validator-4.3.0.Final.jar
/usr/share/java/.m2/repository/org/hibernate/hibernate-validator/4.3.0.Final/hibernate-validator-4.3.0.Final.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-hibernate-validator/copyright.txt
/usr/share/package-licenses/mvn-hibernate-validator/license.txt
